name: resource_finder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.4.1
  geolocator: ^14.0.2  
  shared_preferences: ^2.2.2  
  url_launcher: ^6.2.2 
  flutter_dotenv: ^5.0.2
  image_picker: ^0.8.7+5
  intl: ^0.18.1 
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  google_sign_in: ^6.2.4 
  geocoding: ^3.0.0
  share_plus: ^7.2.1
  crypto: ^3.0.3
  speech_to_text: ^7.3.0        
  permission_handler: ^12.0.1    
  http: ^1.6.0                    
  flutter_tts: ^3.8.5   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - .env

